# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13oeeJpXqlCgQMzIJ7c2_R7njjp6Ew5eE
"""

import streamlit as st
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, accuracy_score

# Replace the current URL with the raw file URL
url = 'https://raw.githubusercontent.com/Sandi-10/Personality/main/personality_dataset.csv'
df = pd.read_csv(url)

# Sidebar navigasi
st.sidebar.title("Navigasi")
page = st.sidebar.radio("Pilih Halaman:", ["Informasi", "Pemodelan Data", "Prediksi"])

# Halaman Informasi
if page == "Informasi":
    st.title("Informasi Dataset")
    st.write("Dataset ini berisi data kepribadian berdasarkan berbagai aspek.")
    st.subheader("Contoh Data")
    st.dataframe(df.head())

    st.subheader("Deskripsi Kolom")
    st.write(df.describe(include='all'))

    st.subheader("Distribusi Target (Personality Type)")
    st.bar_chart(df['Personality'].value_counts())

# Halaman Pemodelan Data
elif page == "Pemodelan Data":
    st.title("Pemodelan Data")

    # Preprocessing
    df_model = df.copy()
    label_encoder = LabelEncoder()
    df_model['Personality'] = label_encoder.fit_transform(df_model['Personality'])

    X = df_model.drop('Personality', axis=1)
    y = df_model['Personality']

    # Cek apakah semua fitur numerik, jika tidak, konversi
    for col in X.columns:
        if X[col].dtype == 'object':
            X[col] = label_encoder.fit_transform(X[col])

    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

    model = RandomForestClassifier()
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)

    acc = accuracy_score(y_test, y_pred)

    st.subheader("Akurasi Model")
    st.write(f"Akurasi: {acc:.2f}")

    st.subheader("Classification Report")
    st.text(classification_report(y_test, y_pred, target_names=label_encoder.classes_))

# Halaman Prediksi
elif page == "Prediksi":
    st.title("Prediksi Kepribadian")

    st.write("Masukkan nilai fitur untuk memprediksi tipe kepribadian:")

    # Asumsi beberapa kolom numerik
    input_data = {}
    for col in df.columns:
        if col != 'Personality':
            if df[col].dtype in [np.float64, np.int64]:
                val = st.number_input(f"{col}", float(df[col].min()), float(df[col].max()), float(df[col].mean()))
            else:
                val = st.selectbox(f"{col}", sorted(df[col].unique()))
            input_data[col] = val

    if st.button("Prediksi"):
        # Preprocessing input
        input_df = pd.DataFrame([input_data])
        # Re-initialize label_encoder to ensure it has seen all categories from the original df
        label_encoder = LabelEncoder()
        label_encoder.fit(df['Personality']) # Fit on the original target column first

        for col in input_df.columns:
             if input_df[col].dtype == 'object':
                 # For categorical input columns, ensure the encoder is fitted on the original df values
                 le_input = LabelEncoder()
                 le_input.fit(df[col]) # Fit on original column
                 input_df[col] = le_input.transform(input_df[col])


        prediction = model.predict(input_df)[0]
        predicted_label = label_encoder.inverse_transform([prediction])[0]

        st.success(f"Tipe Kepribadian yang Diprediksi: {predicted_label}")